# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 411, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.question = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.question.setAlignment(QtCore.Qt.AlignCenter)
        self.question.setObjectName("question")
        self.verticalLayout.addWidget(self.question)
        self.option_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.option_1.setObjectName("option_1")
        self.verticalLayout.addWidget(self.option_1)
        self.option_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.option_2.setObjectName("option_2")
        self.verticalLayout.addWidget(self.option_2)
        self.option_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.option_3.setObjectName("option_3")
        self.verticalLayout.addWidget(self.option_3)
        self.option_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.option_4.setObjectName("option_4")
        self.verticalLayout.addWidget(self.option_4)
        self.result = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        self.nextq = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nextq.setObjectName("nextq")
        self.verticalLayout.addWidget(self.nextq)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    '''def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.question.setText(_translate("MainWindow", "TextLabel"))
        self.option_1.setText(_translate("MainWindow", "PushButton"))
        self.option_2.setText(_translate("MainWindow", "PushButton"))
        self.option_3.setText(_translate("MainWindow", "PushButton"))
        self.option_4.setText(_translate("MainWindow", "PushButton"))
        self.result.setText(_translate("MainWindow", "TextLabel"))
        self.nextq.setText(_translate("MainWindow", "PushButton"))'''
